definitions:
  controllers.scheduledJob:
    properties:
      cron:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  dto.AgentDto:
    properties:
      agent_stack:
        type: string
      agent_version:
        type: string
      id:
        type: string
      last_seen_at:
        type: string
      registered_at:
        type: string
      service:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Aurelius REST API
paths:
  /agents:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.AgentDto'
            type: array
      summary: Get all agents
      tags:
      - agents
  /jobs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.scheduledJob'
            type: array
      summary: Get all scheduled jobs
      tags:
      - jobs
swagger: "2.0"
