definitions:
  dto.AgentDto:
    properties:
      agent_stack:
        type: string
      agent_version:
        type: string
      id:
        type: string
      last_seen_at:
        type: string
      registered_at:
        type: string
      service:
        type: string
    type: object
  dto.JobDto:
    properties:
      agentId:
        type: string
      finishedAt:
        type: string
      id:
        type: string
      name:
        type: string
      startedAt:
        type: string
      version:
        type: string
    type: object
  dto.JobInput:
    properties:
      cron:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Aurelius REST API
paths:
  /agents:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.AgentDto'
            type: array
      summary: Get all agents
      tags:
      - agents
  /jobs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.JobDto'
            type: array
      summary: Get all scheduled jobs
      tags:
      - jobs
  /jobs/{id}:
    patch:
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: string
      - description: Job input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.JobInput'
      produces:
      - application/json
      responses:
        "200":
          description: Job updated successfully
          schema:
            type: string
      summary: Update a scheduled job
      tags:
      - jobs
swagger: "2.0"
