version: '3.9'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: aurelius
      MYSQL_USER: aurelius
      MYSQL_PASSWORD: aurelius
    volumes:
      - ./mysql-data:/var/lib/mysql
